services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    command: >
      sh -c "python src/manage.py migrate &&
             python src/manage.py collectstatic --noinput &&
             python src/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/src/static
      - media_volume:/app/src/media
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge
